ci: add biome ci and reviewdog
SIMDE-ULL/SIMDE pull request #136
Opened 2024-03-29 14:35 UTC by endes0

Closes #70. 

For this PR to be ready, #135 should be finished & merged.

2024-03-29 15:32 UTC, oxcabe requested changes
This seems good for a temporal solution until I finish implementing Nix flake(s) for developing, building and CI.

2024-03-29 15:32 UTC, oxcabe commented on .github/workflows/review.yml
I don't think this is needed with the build workflow additions.

2024-03-30 16:21 UTC, endes0 commented on .github/workflows/review.yml
I think it would be cool to also have a bot that tells you the linter errors in a code review instead of only having a PR check failing, it could be more attractive to new users who don't have biome integrated tin their IDE or don't know about the lint command. But yeah, it's redundant, we can remove it.

2024-03-31 15:16 UTC, oxcabe commented on .github/workflows/review.yml
In fact the best solution, IMO, would be to remove the linting command from the `build.yml` workflow and have reviewdog manage that instead.

I like reviewdog since it can also be configured to run [actionlint](https://github.com/rhysd/actionlint), which is a tool I use a lot that doesn't have any proper extension support in vscode other than as a [Trunk](https://trunk.io/) plugin (which I personally consider to be too heavy).

I wouldn't mind trying it, but expect tooling in Nix to overtake this in the future, even if it cost us the PR annotations.

2024-03-31 16:38 UTC, endes0 commented on .github/workflows/review.yml
> In fact the best solution, IMO, would be to remove the linting command from the build.yml workflow and have reviewdog manage that instead.

I agree.

> I wouldn't mind trying it, but expect tooling in Nix to overtake this in the future, even if it cost us the PR annotations.

If the CI tools for code quality (lint, fmt...) are **automatically** run before a PR can be merged, I don't have any issue with this.

2024-03-31 17:14 UTC, oxcabe commented on .github/workflows/review.yml
It will both run client-side as a pre-commit/Husky hook **and** as a CI check :slightly_smiling_face:

2024-03-31 17:16 UTC, oxcabe commented on .github/workflows/review.yml
See: https://github.com/cachix/git-hooks.nix

2024-04-01 15:15 UTC, oxcabe commented
Closing this massive PR. We will instead opt for a gradual formatting/lint approach, managed from CI tooling such as reviewdog.

2024-04-01 15:16 UTC, oxcabe commented
The branch should be preserved, though. I will lock the branch in order to avoid deleting it by mistake.

2024-04-01 15:19 UTC, oxcabe commented
Nevermind, this comments are for a different PR, https://github.com/SIMDE-ULL/SIMDE/pull/135

2024-04-01 16:22 UTC, oxcabe requested changes

2024-04-01 16:22 UTC, oxcabe commented on .github/workflows/review.yml
> +          reporter: github-pr-review
Add the newline at the end!

2024-04-01 16:29 UTC, endes0 commented
As we dropped #135 I removed the biome ci step but reviewdog should work fine (it only checks additions in theory).

2024-04-01 17:15 UTC, oxcabe approved these changes
LGTM.

2024-04-01 17:18 UTC, merged